# taken from http://data.okfn.org/data/core/language-codes/r/language-codes-3b2.json
terms:
  - id: eng
    alpha2: en
    term: English
    active: true
  - id: aar
    alpha2: aa
    term: Afar
    active: true
  - id: abk
    alpha2: ab
    term: Abkhazian
    active: true
  - id: afr
    alpha2: af
    term: Afrikaans
    active: true
  - id: aka
    alpha2: ak
    term: Akan
    active: true
  - id: alb
    alpha2: sq
    term: Albanian
    active: true
  - id: amh
    alpha2: am
    term: Amharic
    active: true
  - id: ara
    alpha2: ar
    term: Arabic
    active: true
  - id: arg
    alpha2: an
    term: Aragonese
    active: true
  - id: arm
    alpha2: hy
    term: Armenian
    active: true
  - id: asm
    alpha2: as
    term: Assamese
    active: true
  - id: ava
    alpha2: av
    term: Avaric
    active: true
  - id: ave
    alpha2: ae
    term: Avestan
    active: true
  - id: aym
    alpha2: ay
    term: Aymara
    active: true
  - id: aze
    alpha2: az
    term: Azerbaijani
    active: true
  - id: bak
    alpha2: ba
    term: Bashkir
    active: true
  - id: bam
    alpha2: bm
    term: Bambara
    active: true
  - id: baq
    alpha2: eu
    term: Basque
    active: true
  - id: bel
    alpha2: be
    term: Belarusian
    active: true
  - id: ben
    alpha2: bn
    term: Bengali
    active: true
  - id: bih
    alpha2: bh
    term: Bihari languages
    active: true
  - id: bis
    alpha2: bi
    term: Bislama
    active: true
  - id: bos
    alpha2: bs
    term: Bosnian
    active: true
  - id: bre
    alpha2: br
    term: Breton
    active: true
  - id: bul
    alpha2: bg
    term: Bulgarian
    active: true
  - id: bur
    alpha2: my
    term: Burmese
    active: true
  - id: cat
    alpha2: ca
    term: Catalan; Valencian
    active: true
  - id: cha
    alpha2: ch
    term: Chamorro
    active: true
  - id: che
    alpha2: ce
    term: Chechen
    active: true
  - id: chi
    alpha2: zh
    term: Chinese
    active: true
  - id: chu
    alpha2: cu
    term: Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church
      Slavonic
    active: true
  - id: chv
    alpha2: cv
    term: Chuvash
    active: true
  - id: cor
    alpha2: kw
    term: Cornish
    active: true
  - id: cos
    alpha2: co
    term: Corsican
    active: true
  - id: cre
    alpha2: cr
    term: Cree
    active: true
  - id: cze
    alpha2: cs
    term: Czech
    active: true
  - id: dan
    alpha2: da
    term: Danish
    active: true
  - id: div
    alpha2: dv
    term: Divehi; Dhivehi; Maldivian
    active: true
  - id: dut
    alpha2: nl
    term: Dutch; Flemish
    active: true
  - id: dzo
    alpha2: dz
    term: Dzongkha
    active: true
  - id: epo
    alpha2: eo
    term: Esperanto
    active: true
  - id: est
    alpha2: et
    term: Estonian
    active: true
  - id: ewe
    alpha2: ee
    term: Ewe
    active: true
  - id: fao
    alpha2: fo
    term: Faroese
    active: true
  - id: fij
    alpha2: fj
    term: Fijian
    active: true
  - id: fin
    alpha2: fi
    term: Finnish
    active: true
  - id: fre
    alpha2: fr
    term: French
    active: true
  - id: fry
    alpha2: fy
    term: Western Frisian
    active: true
  - id: ful
    alpha2: ff
    term: Fulah
    active: true
  - id: geo
    alpha2: ka
    term: Georgian
    active: true
  - id: ger
    alpha2: de
    term: German
    active: true
  - id: gla
    alpha2: gd
    term: Gaelic; Scottish Gaelic
    active: true
  - id: gle
    alpha2: ga
    term: Irish
    active: true
  - id: glg
    alpha2: gl
    term: Galician
    active: true
  - id: glv
    alpha2: gv
    term: Manx
    active: true
  - id: gre
    alpha2: el
    term: Greek, Modern (1453-)
    active: true
  - id: grn
    alpha2: gn
    term: Guarani
    active: true
  - id: guj
    alpha2: gu
    term: Gujarati
    active: true
  - id: hat
    alpha2: ht
    term: Haitian; Haitian Creole
    active: true
  - id: hau
    alpha2: ha
    term: Hausa
    active: true
  - id: heb
    alpha2: he
    term: Hebrew
    active: true
  - id: her
    alpha2: hz
    term: Herero
    active: true
  - id: hin
    alpha2: hi
    term: Hindi
    active: true
  - id: hmo
    alpha2: ho
    term: Hiri Motu
    active: true
  - id: hrv
    alpha2: hr
    term: Croatian
    active: true
  - id: hun
    alpha2: hu
    term: Hungarian
    active: true
  - id: ibo
    alpha2: ig
    term: Igbo
    active: true
  - id: ice
    alpha2: is
    term: Icelandic
    active: true
  - id: ido
    alpha2: io
    term: Ido
    active: true
  - id: iii
    alpha2: ii
    term: Sichuan Yi; Nuosu
    active: true
  - id: iku
    alpha2: iu
    term: Inuktitut
    active: true
  - id: ile
    alpha2: ie
    term: Interlingue; Occidental
    active: true
  - id: ina
    alpha2: ia
    term: Interlingua (International Auxiliary Language Association)
    active: true
  - id: ind
    alpha2: id
    term: Indonesian
    active: true
  - id: ipk
    alpha2: ik
    term: Inupiaq
    active: true
  - id: ita
    alpha2: it
    term: Italian
    active: true
  - id: jav
    alpha2: jv
    term: Javanese
    active: true
  - id: jpn
    alpha2: ja
    term: Japanese
    active: true
  - id: kal
    alpha2: kl
    term: Kalaallisut; Greenlandic
    active: true
  - id: kan
    alpha2: kn
    term: Kannada
    active: true
  - id: kas
    alpha2: ks
    term: Kashmiri
    active: true
  - id: kau
    alpha2: kr
    term: Kanuri
    active: true
  - id: kaz
    alpha2: kk
    term: Kazakh
    active: true
  - id: khm
    alpha2: km
    term: Central Khmer
    active: true
  - id: kik
    alpha2: ki
    term: Kikuyu; Gikuyu
    active: true
  - id: kin
    alpha2: rw
    term: Kinyarwanda
    active: true
  - id: kir
    alpha2: ky
    term: Kirghiz; Kyrgyz
    active: true
  - id: kom
    alpha2: kv
    term: Komi
    active: true
  - id: kon
    alpha2: kg
    term: Kongo
    active: true
  - id: kor
    alpha2: ko
    term: Korean
    active: true
  - id: kua
    alpha2: kj
    term: Kuanyama; Kwanyama
    active: true
  - id: kur
    alpha2: ku
    term: Kurdish
    active: true
  - id: lao
    alpha2: lo
    term: Lao
    active: true
  - id: lat
    alpha2: la
    term: Latin
    active: true
  - id: lav
    alpha2: lv
    term: Latvian
    active: true
  - id: lim
    alpha2: li
    term: Limburgan; Limburger; Limburgish
    active: true
  - id: lin
    alpha2: ln
    term: Lingala
    active: true
  - id: lit
    alpha2: lt
    term: Lithuanian
    active: true
  - id: ltz
    alpha2: lb
    term: Luxembourgish; Letzeburgesch
    active: true
  - id: lub
    alpha2: lu
    term: Luba-Katanga
    active: true
  - id: lug
    alpha2: lg
    term: Ganda
    active: true
  - id: mac
    alpha2: mk
    term: Macedonian
    active: true
  - id: mah
    alpha2: mh
    term: Marshallese
    active: true
  - id: mal
    alpha2: ml
    term: Malayalam
    active: true
  - id: mao
    alpha2: mi
    term: Maori
    active: true
  - id: mar
    alpha2: mr
    term: Marathi
    active: true
  - id: may
    alpha2: ms
    term: Malay
    active: true
  - id: mlg
    alpha2: mg
    term: Malagasy
    active: true
  - id: mlt
    alpha2: mt
    term: Maltese
    active: true
  - id: mon
    alpha2: mn
    term: Mongolian
    active: true
  - id: nau
    alpha2: na
    term: Nauru
    active: true
  - id: nav
    alpha2: nv
    term: Navajo; Navaho
    active: true
  - id: nbl
    alpha2: nr
    term: Ndebele, South; South Ndebele
    active: true
  - id: nde
    alpha2: nd
    term: Ndebele, North; North Ndebele
    active: true
  - id: ndo
    alpha2: ng
    term: Ndonga
    active: true
  - id: nep
    alpha2: ne
    term: Nepali
    active: true
  - id: nno
    alpha2: nn
    term: Norwegian Nynorsk; Nynorsk, Norwegian
    active: true
  - id: nob
    alpha2: nb
    term: Bokmål, Norwegian; Norwegian Bokmål
    active: true
  - id: nor
    alpha2: 'no'
    term: Norwegian
    active: true
  - id: nya
    alpha2: ny
    term: Chichewa; Chewa; Nyanja
    active: true
  - id: oci
    alpha2: oc
    term: Occitan (post 1500); Provençal
    active: true
  - id: oji
    alpha2: oj
    term: Ojibwa
    active: true
  - id: ori
    alpha2: or
    term: Oriya
    active: true
  - id: orm
    alpha2: om
    term: Oromo
    active: true
  - id: oss
    alpha2: os
    term: Ossetian; Ossetic
    active: true
  - id: pan
    alpha2: pa
    term: Panjabi; Punjabi
    active: true
  - id: per
    alpha2: fa
    term: Persian
    active: true
  - id: pli
    alpha2: pi
    term: Pali
    active: true
  - id: pol
    alpha2: pl
    term: Polish
    active: true
  - id: por
    alpha2: pt
    term: Portuguese
    active: true
  - id: pus
    alpha2: ps
    term: Pushto; Pashto
    active: true
  - id: que
    alpha2: qu
    term: Quechua
    active: true
  - id: roh
    alpha2: rm
    term: Romansh
    active: true
  - id: rum
    alpha2: ro
    term: Romanian; Moldavian; Moldovan
    active: true
  - id: run
    alpha2: rn
    term: Rundi
    active: true
  - id: rus
    alpha2: ru
    term: Russian
    active: true
  - id: sag
    alpha2: sg
    term: Sango
    active: true
  - id: san
    alpha2: sa
    term: Sanskrit
    active: true
  - id: sin
    alpha2: si
    term: Sinhala; Sinhalese
    active: true
  - id: slo
    alpha2: sk
    term: Slovak
    active: true
  - id: slv
    alpha2: sl
    term: Slovenian
    active: true
  - id: sme
    alpha2: se
    term: Northern Sami
    active: true
  - id: smo
    alpha2: sm
    term: Samoan
    active: true
  - id: sna
    alpha2: sn
    term: Shona
    active: true
  - id: snd
    alpha2: sd
    term: Sindhi
    active: true
  - id: som
    alpha2: so
    term: Somali
    active: true
  - id: sot
    alpha2: st
    term: Sotho, Southern
    active: true
  - id: spa
    alpha2: es
    term: Spanish; Castilian
    active: true
  - id: srd
    alpha2: sc
    term: Sardinian
    active: true
  - id: srp
    alpha2: sr
    term: Serbian
    active: true
  - id: ssw
    alpha2: ss
    term: Swati
    active: true
  - id: sun
    alpha2: su
    term: Sundanese
    active: true
  - id: swa
    alpha2: sw
    term: Swahili
    active: true
  - id: swe
    alpha2: sv
    term: Swedish
    active: true
  - id: tah
    alpha2: ty
    term: Tahitian
    active: true
  - id: tam
    alpha2: ta
    term: Tamil
    active: true
  - id: tat
    alpha2: tt
    term: Tatar
    active: true
  - id: tel
    alpha2: te
    term: Telugu
    active: true
  - id: tgk
    alpha2: tg
    term: Tajik
    active: true
  - id: tgl
    alpha2: tl
    term: Tagalog
    active: true
  - id: tha
    alpha2: th
    term: Thai
    active: true
  - id: tib
    alpha2: bo
    term: Tibetan
    active: true
  - id: tir
    alpha2: ti
    term: Tigrinya
    active: true
  - id: ton
    alpha2: to
    term: Tonga (Tonga Islands)
    active: true
  - id: tsn
    alpha2: tn
    term: Tswana
    active: true
  - id: tso
    alpha2: ts
    term: Tsonga
    active: true
  - id: tuk
    alpha2: tk
    term: Turkmen
    active: true
  - id: tur
    alpha2: tr
    term: Turkish
    active: true
  - id: twi
    alpha2: tw
    term: Twi
    active: true
  - id: uig
    alpha2: ug
    term: Uighur; Uyghur
    active: true
  - id: ukr
    alpha2: uk
    term: Ukrainian
    active: true
  - id: urd
    alpha2: ur
    term: Urdu
    active: true
  - id: uzb
    alpha2: uz
    term: Uzbek
    active: true
  - id: ven
    alpha2: ve
    term: Venda
    active: true
  - id: vie
    alpha2: vi
    term: Vietnamese
    active: true
  - id: vol
    alpha2: vo
    term: Volapük
    active: true
  - id: wel
    alpha2: cy
    term: Welsh
    active: true
  - id: wln
    alpha2: wa
    term: Walloon
    active: true
  - id: wol
    alpha2: wo
    term: Wolof
    active: true
  - id: xho
    alpha2: xh
    term: Xhosa
    active: true
  - id: yid
    alpha2: yi
    term: Yiddish
    active: true
  - id: yor
    alpha2: yo
    term: Yoruba
    active: true
  - id: zha
    alpha2: za
    term: Zhuang; Chuang
    active: true
  - id: zul
    alpha2: zu
    term: Zulu
