development:
  adapter: solr
  #url: <%= ENV['SOLR_DEV_URL'] %>
  #url: http://127.0.0.1:8983/solr/development
  #url: http://dlibsolrdev0.york.ac.uk:8983/solr/hydra_peri
  url: http://dlibsolrdev0.york.ac.uk:8983/solr/hydra_peri
test:
  adapter: solr
  url: http://localhost:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

