development:
  user: fedoraAdmin
  password: fedoraAdmin
  #url: http://127.0.0.1:<%= ENV['FCREPO_DEVELOPMENT_PORT'] || 8984 %>/rest
  #url: http://127.0.0.1:8080/fedora/rest
  url: http://dlibfeddev0.york.ac.uk:8080/fedora/rest
  # base_path: <%= ENV['FCREPO_DEV_BASE'] %>
  base_path: /peri_dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:<%= ENV['FCREPO_TEST_PORT'] || 8986 %>/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora/rest
  base_path: /prod
