# Generated by curation_concerns:models:install
class Collection < Dlibhydra::Collection #ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior
  # You can replace these metadata if they're not suitable
  # include CurationConcerns::BasicMetadata

  self.human_readable_type = 'Collection'
  validates :title, presence: {message: 'Your collection must have a title.'}

  class CollectionIndexer < CurationConcerns::CollectionIndexer # Hydra::PCDM::PCDMIndexer
    include Dlibhydra::IndexesCollection
  end

  def self.indexer
    CollectionIndexer
  end
end
