# Generated by curation_concerns:models:install
class FileSet < Dlibhydra::FileSet #ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior

  self.human_readable_type = 'FileSet'

  # might need an indexer?
end
